services:
  db:
    image: pgvector/pgvector:pg16
    container_name: rag-postgres-db
    hostname: rag-postgres-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - rag-db-data:/var/lib/postgresql/data

volumes:
  rag-db-data:
